### ISSUE TITLE
A Life in Music: A novel generated from your music files

### ISSUE THREAD

**Issue by katstasaph** [NaNoGenMo/2022#20]
This will generate a novel based on your local music files.

Repo: https://github.com/katstasaph/a-life-in-music

The plot will be simple: you are downsizing your local music library and feeling ambivalent; you go through the songs, reminisce, and decide what to keep. (NOTE: Goes without saying, but this does not actually delete your files.) 

To generate the actual content, it will most likely use some combination of the following:

- File metadata on artist, song, etc
- File creation/modification/access, to see whether you last listened to a song late at night, etc. (this does not totally correspond to reality, unfortunately, due to a lot of factors; for instance, if you add a folder to Winamp, every single file counts as accessed)
- File listening stats from iTunes, in my case (also incomplete since I have used Winamp all my life, but not nothing)
- Possibly song info from some music API for non-quantifiable stuff)

## Log

11/2/2022: Created the project shell. Right now it isn't much of a novel; it just prints the filenames in one folder, along with their modified date (which will be used later, not in this form).

**Comment by sermo-de-arboribus** [comment]
I love the idea! I don't know if this is feasible, but some mp3 files might contain a tag with the lyrics of the song. Maybe that's something that you could use as well?

**Comment by katstasaph** [comment]
have been hemorrhaging time, let's do this next year
